# Generated by Django 6.0.6 on 2026-07-02 10:31

import compapp.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.PositiveSmallIntegerField(default=70)),
                ('max_width', models.PositiveIntegerField(default=1920)),
                ('output_format', models.CharField(default='JPEG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(upload_to=compapp.models.original_upload_path)),
                ('compressed_file', models.ImageField(blank=True, null=True, upload_to=compapp.models.compressed_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('original_size', models.PositiveIntegerField(default=0)),
                ('compressed_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='compapp.uploadbatch')),
            ],
        ),
    ]
