# Generated by Django 6.0.6 on 2026-07-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='remove_background',
            field=models.BooleanField(default=False),
        ),
    ]
